name: Build LaTeX Resume

on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'
      - '.github/workflows/latex.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume-peyton-spencer.tex

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: resume-peyton-spencer.pdf
          tag_name: v${{ github.run_number }}
          name: Resume Build ${{ github.run_number }}
          body: |
            Automated resume build from commit ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}